/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_number = 2,
  anon_sym_DQUOTE = 3,
  aux_sym_string_token1 = 4,
  aux_sym_string_token2 = 5,
  sym_var_rest_pattern = 6,
  sym_var_pattern = 7,
  sym_symbol = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  aux_sym_function_call_token1 = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_COMMA = 14,
  sym_source_file = 15,
  sym_expression = 16,
  sym_string = 17,
  sym_brace_call = 18,
  sym_function_call = 19,
  sym__argument_list = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_string_repeat1 = 22,
  aux_sym__argument_list_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_var_rest_pattern] = "var_rest_pattern",
  [sym_var_pattern] = "var_pattern",
  [sym_symbol] = "symbol",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_function_call_token1] = "symbol",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_string] = "string",
  [sym_brace_call] = "brace_call",
  [sym_function_call] = "function_call",
  [sym__argument_list] = "_argument_list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym__argument_list_repeat1] = "_argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_var_rest_pattern] = sym_var_rest_pattern,
  [sym_var_pattern] = sym_var_pattern,
  [sym_symbol] = sym_symbol,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_function_call_token1] = sym_symbol,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_string] = sym_string,
  [sym_brace_call] = sym_brace_call,
  [sym_function_call] = sym_function_call,
  [sym__argument_list] = sym__argument_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym__argument_list_repeat1] = aux_sym__argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_var_rest_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_var_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_function_call_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__argument_list] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_function = 2,
  field_head = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
  [field_head] = "head",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
  [1] =
    {field_head, 1},
  [2] =
    {field_arguments, 2},
    {field_function, 0},
  [4] =
    {field_arguments, 2},
    {field_head, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 5,
  [9] = 3,
  [10] = 2,
  [11] = 5,
  [12] = 3,
  [13] = 2,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 14,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 21,
  [32] = 32,
  [33] = 22,
  [34] = 26,
  [35] = 24,
  [36] = 32,
  [37] = 30,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 39,
  [42] = 39,
  [43] = 43,
  [44] = 38,
  [45] = 18,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 24,
  [50] = 26,
  [51] = 25,
  [52] = 30,
  [53] = 21,
  [54] = 32,
  [55] = 22,
  [56] = 20,
  [57] = 28,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 59,
  [64] = 61,
  [65] = 59,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', ':'}, {'<', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 20,
        '(', 49,
        ')', 50,
        ',', 51,
        '-', 43,
        '.', 40,
        '/', 34,
        ';', 17,
        '\\', 33,
        '_', 32,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 6:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 20,
        '(', 49,
        ')', 50,
        '-', 43,
        '.', 40,
        '/', 34,
        ';', 17,
        '_', 32,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < ',' || '9' < lookahead)) ADVANCE(46);
      END_STATE();
    case 7:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 20,
        ')', 50,
        ',', 51,
        '-', 43,
        '.', 40,
        '/', 34,
        ';', 17,
        '\\', 33,
        '_', 32,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 8:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 20,
        ')', 50,
        '-', 43,
        '.', 40,
        '/', 34,
        ';', 17,
        '_', 32,
        '{', 47,
        '}', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < ',' || '9' < lookahead)) ADVANCE(46);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == ',') ADVANCE(51);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ';') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_var_rest_pattern);
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_var_rest_pattern);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_var_rest_pattern);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_var_pattern);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '_') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_var_pattern);
      if (lookahead == '_') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(22);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '/') ADVANCE(14);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(3);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(30);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(39);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '/') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(3);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_symbol);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [sym_var_rest_pattern] = ACTIONS(1),
    [sym_var_pattern] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_function_call_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_expression] = STATE(4),
    [sym_string] = STATE(35),
    [sym_brace_call] = STATE(35),
    [sym_function_call] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_var_rest_pattern] = ACTIONS(9),
    [sym_var_pattern] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_function_call_token1] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(7),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(31),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(2),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(35),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(6),
    [sym_string] = STATE(35),
    [sym_brace_call] = STATE(35),
    [sym_function_call] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_var_rest_pattern] = ACTIONS(9),
    [sym_var_pattern] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_function_call_token1] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(48),
    [sym_string] = STATE(49),
    [sym_brace_call] = STATE(49),
    [sym_function_call] = STATE(49),
    [sym__argument_list] = STATE(64),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_var_rest_pattern] = ACTIONS(43),
    [sym_var_pattern] = ACTIONS(45),
    [sym_symbol] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(49),
    [aux_sym_function_call_token1] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(53),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(6),
    [sym_string] = STATE(35),
    [sym_brace_call] = STATE(35),
    [sym_function_call] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(60),
    [sym_var_rest_pattern] = ACTIONS(63),
    [sym_var_pattern] = ACTIONS(66),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(72),
    [aux_sym_function_call_token1] = ACTIONS(75),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(7),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_var_rest_pattern] = ACTIONS(84),
    [sym_var_pattern] = ACTIONS(87),
    [sym_symbol] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(55),
    [aux_sym_function_call_token1] = ACTIONS(96),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(48),
    [sym_string] = STATE(49),
    [sym_brace_call] = STATE(49),
    [sym_function_call] = STATE(49),
    [sym__argument_list] = STATE(61),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_var_rest_pattern] = ACTIONS(43),
    [sym_var_pattern] = ACTIONS(45),
    [sym_symbol] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(49),
    [aux_sym_function_call_token1] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(99),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(10),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(101),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
  [STATE(10)] = {
    [sym_expression] = STATE(7),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(103),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
  [STATE(11)] = {
    [sym_expression] = STATE(48),
    [sym_string] = STATE(49),
    [sym_brace_call] = STATE(49),
    [sym_function_call] = STATE(49),
    [sym__argument_list] = STATE(62),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_var_rest_pattern] = ACTIONS(43),
    [sym_var_pattern] = ACTIONS(45),
    [sym_symbol] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(49),
    [aux_sym_function_call_token1] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(105),
  },
  [STATE(12)] = {
    [sym_expression] = STATE(13),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(13),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(107),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
  [STATE(13)] = {
    [sym_expression] = STATE(7),
    [sym_string] = STATE(24),
    [sym_brace_call] = STATE(24),
    [sym_function_call] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_var_rest_pattern] = ACTIONS(23),
    [sym_var_pattern] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(109),
    [aux_sym_function_call_token1] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_var_rest_pattern,
    ACTIONS(25), 1,
      sym_var_pattern,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      aux_sym_function_call_token1,
    STATE(3), 1,
      sym_expression,
    STATE(24), 3,
      sym_string,
      sym_brace_call,
      sym_function_call,
  [33] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_number,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_var_rest_pattern,
    ACTIONS(45), 1,
      sym_var_pattern,
    ACTIONS(47), 1,
      sym_symbol,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      aux_sym_function_call_token1,
    STATE(58), 1,
      sym_expression,
    STATE(49), 3,
      sym_string,
      sym_brace_call,
      sym_function_call,
  [66] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_var_rest_pattern,
    ACTIONS(25), 1,
      sym_var_pattern,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      aux_sym_function_call_token1,
    STATE(9), 1,
      sym_expression,
    STATE(24), 3,
      sym_string,
      sym_brace_call,
      sym_function_call,
  [99] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_var_rest_pattern,
    ACTIONS(25), 1,
      sym_var_pattern,
    ACTIONS(27), 1,
      sym_symbol,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      aux_sym_function_call_token1,
    STATE(12), 1,
      sym_expression,
    STATE(24), 3,
      sym_string,
      sym_brace_call,
      sym_function_call,
  [132] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [151] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(119), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [186] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(125), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(129), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(119), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [234] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [266] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [298] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(131), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [314] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(131), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(135), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [346] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(125), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(139), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(129), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [410] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(113), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(139), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(135), 5,
      sym_number,
      sym_var_rest_pattern,
      sym_var_pattern,
      sym_symbol,
      aux_sym_function_call_token1,
  [458] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(145), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [472] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_string_repeat1,
    ACTIONS(149), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [486] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_string_repeat1,
    ACTIONS(153), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [500] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_string_repeat1,
    ACTIONS(149), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [514] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_string_repeat1,
    ACTIONS(149), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [528] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_string_repeat1,
    ACTIONS(161), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [542] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(166), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [556] = 3,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [567] = 4,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym__argument_list_repeat1,
  [580] = 4,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym__argument_list_repeat1,
  [593] = 4,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym__argument_list_repeat1,
  [606] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [614] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [622] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [630] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [638] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [646] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [654] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [662] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [670] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [678] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [686] = 2,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 1,
      sym_comment,
  [693] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
  [700] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
  [707] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
  [714] = 2,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 1,
      sym_comment,
  [721] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [728] = 2,
    ACTIONS(168), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 33,
  [SMALL_STATE(16)] = 66,
  [SMALL_STATE(17)] = 99,
  [SMALL_STATE(18)] = 132,
  [SMALL_STATE(19)] = 151,
  [SMALL_STATE(20)] = 170,
  [SMALL_STATE(21)] = 186,
  [SMALL_STATE(22)] = 202,
  [SMALL_STATE(23)] = 218,
  [SMALL_STATE(24)] = 234,
  [SMALL_STATE(25)] = 250,
  [SMALL_STATE(26)] = 266,
  [SMALL_STATE(27)] = 282,
  [SMALL_STATE(28)] = 298,
  [SMALL_STATE(29)] = 314,
  [SMALL_STATE(30)] = 330,
  [SMALL_STATE(31)] = 346,
  [SMALL_STATE(32)] = 362,
  [SMALL_STATE(33)] = 378,
  [SMALL_STATE(34)] = 394,
  [SMALL_STATE(35)] = 410,
  [SMALL_STATE(36)] = 426,
  [SMALL_STATE(37)] = 442,
  [SMALL_STATE(38)] = 458,
  [SMALL_STATE(39)] = 472,
  [SMALL_STATE(40)] = 486,
  [SMALL_STATE(41)] = 500,
  [SMALL_STATE(42)] = 514,
  [SMALL_STATE(43)] = 528,
  [SMALL_STATE(44)] = 542,
  [SMALL_STATE(45)] = 556,
  [SMALL_STATE(46)] = 567,
  [SMALL_STATE(47)] = 580,
  [SMALL_STATE(48)] = 593,
  [SMALL_STATE(49)] = 606,
  [SMALL_STATE(50)] = 614,
  [SMALL_STATE(51)] = 622,
  [SMALL_STATE(52)] = 630,
  [SMALL_STATE(53)] = 638,
  [SMALL_STATE(54)] = 646,
  [SMALL_STATE(55)] = 654,
  [SMALL_STATE(56)] = 662,
  [SMALL_STATE(57)] = 670,
  [SMALL_STATE(58)] = 678,
  [SMALL_STATE(59)] = 686,
  [SMALL_STATE(60)] = 693,
  [SMALL_STATE(61)] = 700,
  [SMALL_STATE(62)] = 707,
  [SMALL_STATE(63)] = 714,
  [SMALL_STATE(64)] = 721,
  [SMALL_STATE(65)] = 728,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_call, 4, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_call, 4, 0, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_call, 3, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_call, 3, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_syma(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "syma",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
